name: Update API Data

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule to run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Fetch and store API data
      run: node fetch-api-data.js

    - name: Commit and push changes
      run: |
        git config --local user.email "peterbenoit@gmail.com"
        git config --local user.name "Peter Benoit"
        git add .
        git status  # Check the status before committing
        git commit -m "Update API data"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/peterbenoit/RealEstateMarket.git HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}